### ISSUE TITLE
NameID format is hardcoded (AuthnRequest)

### ISSUE THREAD

**Issue by arteniioleg** [lightSAML/SpBundle#54]
https://github.com/lightSAML/lightSAML/blob/d0253368b7eba88e867545ab3590cbcc7fa8b04d/src/LightSaml/Action/Profile/Outbound/Message/CreateMessageIssuerAction.php#L36

**Comment by arteniioleg** [comment]
#### How to trigger LightSaml events on Symfony event disptacher

Set in `config.yml`

```yaml
light_saml_symfony_bridge:
    ...
    system:
        # dispatch LightSaml events on Symfony event dispatcher instead of separate dispatcher
        event_dispatcher: 'event_dispatcher'
```

So the above event can be hooked [as usual](https://symfony.com/doc/current/event_dispatcher.html)

```php
use LightSaml\Event\Events;

public static function getSubscribedEvents()
{
    return [
        Events::BEFORE_ENCRYPT => 'onSamlBeforeEncrypt',
    ];
}
```
