### ISSUE TITLE
switch_user not working

### ISSUE THREAD

**Issue by eluus** [lightSAML/SpBundle#65]
Since I use this bundle (which is working fine), switch_user is not working, I got an error ERR_TOO_MANY_REDIRECTS.

My configuration : 

```
firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            switch_user: true
            light_saml_sp:
                provider: db_provider       # user provider name configured in step 9
                login_path: /saml/login
                check_path: /saml/login_check
                failure_handler: auth_fail
                success_handler: login_handler
            logout:
                path: lightsaml_sp.logout
                target: /
                invalidate_session: false
            anonymous: ~
```
