### ISSUE TITLE
Update user

### ISSUE THREAD

**Issue by katerina-n** [lightSAML/SpBundle#81]
Could you please assist me one more time? Is there any way to update a logged in user info if his name/phone/title were changed? I haven't found any other option except of override AuthenticationSuccessHandlerInterface and put it there. But I suppose that is not the best solution

**Comment by frostieDE** [comment]
One way is to provide a custom `SamlSpTokenFactory` which then dispatches a custom `AuthenticationEvent`. See my implementation ([SamlSpTokenFactory.php](https://github.com/SchulIT/common-bundle/blob/master/Security/Factory/SamlSpTokenFactory.php), [AuthenticationEvent.php](https://github.com/SchulIT/common-bundle/blob/master/Security/AuthenticationEvent.php)).

Do not forget to configure the custom Factory inside your `security.yaml`:

```yaml
...
       secured:
            pattern: ^/
            light_saml_sp:
                provider: database
                user_creator: App\Security\User\UserCreator
                login_path: /saml/login
                check_path: /saml/login_check
                token_factory: App\Security\SamlSpTokenFactory
```

I don't know if it is the best way to do this, but it works for us :smile:

I am not sure why we are not using [Symfony's security events](https://symfony.com/doc/current/components/security/authentication.html#security-events). This should be a better way to do this :-) You may fetch the current [`SamlSpResponseToken`](https://github.com/lightSAML/SpBundle/blob/master/src/LightSaml/SpBundle/Security/Authentication/Token/SamlSpResponseToken.php) which has a method `getResponse()` which should return the SAML Response.
